apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-frontend
  labels:
    app: todolist-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todolist-frontend
  template:
    metadata:
      labels:
        app: todolist-frontend
    spec:
      containers:
      - name: todolist-frontend
        image: garbiozyildiz/todolist-frontend:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: todolist-frontend
  labels:
    app: todolist-frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 4200
    nodePort: 30008
    protocol: TCP
  selector:
    app: todolist-frontend